# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 desc "Push a new beta build to TestFlight"
  lane :beta do
#     xcode_select("/Applications/Xcode-15.3.app")
    Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end
    api_key = app_store_connect_api_key(
        key_id: ENV['KEY_ID'],
        issuer_id: ENV['ISSUER_ID'],
        key_content: ENV['SECRET_KCY'],
        duration: 1200,
        in_house: false
    )

    increment_version_number(
        xcodeproj: "Runner.xcodeproj",
        version_number: flutter_version()["version_name"]
    )
    increment_build_number(
        xcodeproj: "Runner.xcodeproj",
        build_number: flutter_version()["version_code"]
    )
    build_app(
        workspace: "Runner.xcworkspace",
        scheme: "Runner",
        export_options: {
            provisioningProfiles: {
              "com.k1a2.dravel" => "dravel appstore provisioning",
            }
        }
#         export_method: "app-store-connect",
    )
    upload_to_testflight(
        api_key: api_key,
    )
  end
end
